[package]
name = "boggle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typed-arena = "2.0.1"
radix_trie = "0.2.1"
yada = "0.5.0"

[profile.release]
debug = true